// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoList.Data.Context;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(TodoDb))]
    [Migration("20231010132612_Notes3")]
    partial class Notes3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoList.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Группа 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Группа 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Группа 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Группа 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Группа 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Группа 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Группа 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Группа 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Группа 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Группа 10"
                        });
                });

            modelBuilder.Entity("ToDoList.Data.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "Priority", "CreatedDate");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3004),
                            Name = "Задача 1",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3009),
                            Name = "Задача 2",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3011),
                            Name = "Задача 3",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3013),
                            Name = "Задача 4",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3015),
                            Name = "Задача 5",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3017),
                            Name = "Задача 6",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3019),
                            Name = "Задача 7",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3020),
                            Name = "Задача 8",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3022),
                            Name = "Задача 9",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3024),
                            Name = "Задача 10",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3026),
                            Name = "Задача 11",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3028),
                            Name = "Задача 12",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3029),
                            Name = "Задача 13",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3031),
                            Name = "Задача 14",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3033),
                            Name = "Задача 15",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3034),
                            Name = "Задача 16",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3036),
                            Name = "Задача 17",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3037),
                            Name = "Задача 18",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3039),
                            Name = "Задача 19",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3041),
                            Name = "Задача 20",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3042),
                            Name = "Задача 21",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3044),
                            Name = "Задача 22",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3046),
                            Name = "Задача 23",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3047),
                            Name = "Задача 24",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3049),
                            Name = "Задача 25",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3050),
                            Name = "Задача 26",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3052),
                            Name = "Задача 27",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3053),
                            Name = "Задача 28",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3055),
                            Name = "Задача 29",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3057),
                            Name = "Задача 30",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3058),
                            Name = "Задача 31",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3060),
                            Name = "Задача 32",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3061),
                            Name = "Задача 33",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3063),
                            Name = "Задача 34",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3065),
                            Name = "Задача 35",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3066),
                            Name = "Задача 36",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3068),
                            Name = "Задача 37",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3069),
                            Name = "Задача 38",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3070),
                            Name = "Задача 39",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3072),
                            Name = "Задача 40",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3117),
                            Name = "Задача 41",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3119),
                            Name = "Задача 42",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3121),
                            Name = "Задача 43",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3122),
                            Name = "Задача 44",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3124),
                            Name = "Задача 45",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3125),
                            Name = "Задача 46",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3127),
                            Name = "Задача 47",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3128),
                            Name = "Задача 48",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3130),
                            Name = "Задача 49",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3131),
                            Name = "Задача 50",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3133),
                            Name = "Задача 51",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3135),
                            Name = "Задача 52",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3136),
                            Name = "Задача 53",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3138),
                            Name = "Задача 54",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3139),
                            Name = "Задача 55",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3141),
                            Name = "Задача 56",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3142),
                            Name = "Задача 57",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3144),
                            Name = "Задача 58",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3145),
                            Name = "Задача 59",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3147),
                            Name = "Задача 60",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3149),
                            Name = "Задача 61",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3150),
                            Name = "Задача 62",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3152),
                            Name = "Задача 63",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3154),
                            Name = "Задача 64",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3155),
                            Name = "Задача 65",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3157),
                            Name = "Задача 66",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3159),
                            Name = "Задача 67",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3161),
                            Name = "Задача 68",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3162),
                            Name = "Задача 69",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3164),
                            Name = "Задача 70",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3165),
                            Name = "Задача 71",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3167),
                            Name = "Задача 72",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3168),
                            Name = "Задача 73",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3170),
                            Name = "Задача 74",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3172),
                            Name = "Задача 75",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3173),
                            Name = "Задача 76",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3175),
                            Name = "Задача 77",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3176),
                            Name = "Задача 78",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3178),
                            Name = "Задача 79",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3179),
                            Name = "Задача 80",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3181),
                            Name = "Задача 81",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3182),
                            Name = "Задача 82",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3184),
                            Name = "Задача 83",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3186),
                            Name = "Задача 84",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3187),
                            Name = "Задача 85",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3188),
                            Name = "Задача 86",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3190),
                            Name = "Задача 87",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3191),
                            Name = "Задача 88",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3193),
                            Name = "Задача 89",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3195),
                            Name = "Задача 90",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3197),
                            Name = "Задача 91",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3198),
                            Name = "Задача 92",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3200),
                            Name = "Задача 93",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3202),
                            Name = "Задача 94",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3203),
                            Name = "Задача 95",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3205),
                            Name = "Задача 96",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3206),
                            Name = "Задача 97",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3208),
                            Name = "Задача 98",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3210),
                            Name = "Задача 99",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 26, 12, 490, DateTimeKind.Utc).AddTicks(3213),
                            Name = "Задача 100",
                            Priority = "Medium"
                        });
                });

            modelBuilder.Entity("ToDoList.Data.Entities.Note", b =>
                {
                    b.HasOne("ToDoList.Data.Entities.Category", "Category")
                        .WithMany("Notes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ToDoList.Data.Entities.Category", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
