// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoList.Data.Context;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(TodoDb))]
    [Migration("20231010131258_Notes2")]
    partial class Notes2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoList.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Группа 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Группа 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Группа 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Группа 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Группа 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Группа 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Группа 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Группа 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Группа 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Группа 10"
                        });
                });

            modelBuilder.Entity("ToDoList.Data.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "Priority", "CreatedDate");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9456),
                            Name = "Задача 1",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9462),
                            Name = "Задача 2",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9464),
                            Name = "Задача 3",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9466),
                            Name = "Задача 4",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9468),
                            Name = "Задача 5",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9470),
                            Name = "Задача 6",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9472),
                            Name = "Задача 7",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9548),
                            Name = "Задача 8",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9551),
                            Name = "Задача 9",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9554),
                            Name = "Задача 10",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9555),
                            Name = "Задача 11",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9557),
                            Name = "Задача 12",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9559),
                            Name = "Задача 13",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9560),
                            Name = "Задача 14",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9562),
                            Name = "Задача 15",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9564),
                            Name = "Задача 16",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9566),
                            Name = "Задача 17",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9567),
                            Name = "Задача 18",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9569),
                            Name = "Задача 19",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9571),
                            Name = "Задача 20",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9572),
                            Name = "Задача 21",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9574),
                            Name = "Задача 22",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9576),
                            Name = "Задача 23",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9577),
                            Name = "Задача 24",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9579),
                            Name = "Задача 25",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9581),
                            Name = "Задача 26",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9583),
                            Name = "Задача 27",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9584),
                            Name = "Задача 28",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9586),
                            Name = "Задача 29",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9588),
                            Name = "Задача 30",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9590),
                            Name = "Задача 31",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9591),
                            Name = "Задача 32",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9593),
                            Name = "Задача 33",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9595),
                            Name = "Задача 34",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9596),
                            Name = "Задача 35",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9598),
                            Name = "Задача 36",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9599),
                            Name = "Задача 37",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9601),
                            Name = "Задача 38",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9603),
                            Name = "Задача 39",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9604),
                            Name = "Задача 40",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9606),
                            Name = "Задача 41",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9607),
                            Name = "Задача 42",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9609),
                            Name = "Задача 43",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9611),
                            Name = "Задача 44",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9612),
                            Name = "Задача 45",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9614),
                            Name = "Задача 46",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9616),
                            Name = "Задача 47",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9617),
                            Name = "Задача 48",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9619),
                            Name = "Задача 49",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9621),
                            Name = "Задача 50",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9623),
                            Name = "Задача 51",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9625),
                            Name = "Задача 52",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9626),
                            Name = "Задача 53",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9628),
                            Name = "Задача 54",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9629),
                            Name = "Задача 55",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9631),
                            Name = "Задача 56",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9632),
                            Name = "Задача 57",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9634),
                            Name = "Задача 58",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9636),
                            Name = "Задача 59",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9638),
                            Name = "Задача 60",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9639),
                            Name = "Задача 61",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9641),
                            Name = "Задача 62",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9642),
                            Name = "Задача 63",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9644),
                            Name = "Задача 64",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9646),
                            Name = "Задача 65",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9648),
                            Name = "Задача 66",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9650),
                            Name = "Задача 67",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9651),
                            Name = "Задача 68",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9653),
                            Name = "Задача 69",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9655),
                            Name = "Задача 70",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9656),
                            Name = "Задача 71",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9658),
                            Name = "Задача 72",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9660),
                            Name = "Задача 73",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9661),
                            Name = "Задача 74",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9663),
                            Name = "Задача 75",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9665),
                            Name = "Задача 76",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9666),
                            Name = "Задача 77",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9668),
                            Name = "Задача 78",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9669),
                            Name = "Задача 79",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9671),
                            Name = "Задача 80",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9673),
                            Name = "Задача 81",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9674),
                            Name = "Задача 82",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9676),
                            Name = "Задача 83",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9677),
                            Name = "Задача 84",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9679),
                            Name = "Задача 85",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9681),
                            Name = "Задача 86",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9719),
                            Name = "Задача 87",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9721),
                            Name = "Задача 88",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9722),
                            Name = "Задача 89",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9724),
                            Name = "Задача 90",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9726),
                            Name = "Задача 91",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9727),
                            Name = "Задача 92",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9729),
                            Name = "Задача 93",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9731),
                            Name = "Задача 94",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9732),
                            Name = "Задача 95",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9734),
                            Name = "Задача 96",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9736),
                            Name = "Задача 97",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9738),
                            Name = "Задача 98",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9739),
                            Name = "Задача 99",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 13, 12, 57, 891, DateTimeKind.Utc).AddTicks(9741),
                            Name = "Задача 100",
                            Priority = "Low"
                        });
                });

            modelBuilder.Entity("ToDoList.Data.Entities.Note", b =>
                {
                    b.HasOne("ToDoList.Data.Entities.Category", "Category")
                        .WithMany("Notes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ToDoList.Data.Entities.Category", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
