// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoList.Data.Context;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(TodoDb))]
    [Migration("20231010125919_Notes")]
    partial class Notes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoList.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Группа 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Группа 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Группа 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Группа 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Группа 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Группа 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Группа 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Группа 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Группа 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Группа 10"
                        });
                });

            modelBuilder.Entity("ToDoList.Data.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "Priority", "CreatedDate");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4151),
                            Name = "Задача 1",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4159),
                            Name = "Задача 2",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4161),
                            Name = "Задача 3",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4163),
                            Name = "Задача 4",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4165),
                            Name = "Задача 5",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4166),
                            Name = "Задача 6",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4168),
                            Name = "Задача 7",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4170),
                            Name = "Задача 8",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4172),
                            Name = "Задача 9",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4174),
                            Name = "Задача 10",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4175),
                            Name = "Задача 11",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4177),
                            Name = "Задача 12",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4178),
                            Name = "Задача 13",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4180),
                            Name = "Задача 14",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4182),
                            Name = "Задача 15",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4183),
                            Name = "Задача 16",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4185),
                            Name = "Задача 17",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4187),
                            Name = "Задача 18",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4188),
                            Name = "Задача 19",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4190),
                            Name = "Задача 20",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4191),
                            Name = "Задача 21",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4193),
                            Name = "Задача 22",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4195),
                            Name = "Задача 23",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4196),
                            Name = "Задача 24",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4198),
                            Name = "Задача 25",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4199),
                            Name = "Задача 26",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4201),
                            Name = "Задача 27",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4203),
                            Name = "Задача 28",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4205),
                            Name = "Задача 29",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4207),
                            Name = "Задача 30",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4208),
                            Name = "Задача 31",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4210),
                            Name = "Задача 32",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4212),
                            Name = "Задача 33",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4213),
                            Name = "Задача 34",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4215),
                            Name = "Задача 35",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4217),
                            Name = "Задача 36",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4219),
                            Name = "Задача 37",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4220),
                            Name = "Задача 38",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4222),
                            Name = "Задача 39",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4223),
                            Name = "Задача 40",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4225),
                            Name = "Задача 41",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4226),
                            Name = "Задача 42",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4228),
                            Name = "Задача 43",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4314),
                            Name = "Задача 44",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4316),
                            Name = "Задача 45",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4318),
                            Name = "Задача 46",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4320),
                            Name = "Задача 47",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4322),
                            Name = "Задача 48",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4324),
                            Name = "Задача 49",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4326),
                            Name = "Задача 50",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4327),
                            Name = "Задача 51",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4329),
                            Name = "Задача 52",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4331),
                            Name = "Задача 53",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4333),
                            Name = "Задача 54",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4335),
                            Name = "Задача 55",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4337),
                            Name = "Задача 56",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4338),
                            Name = "Задача 57",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4340),
                            Name = "Задача 58",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4342),
                            Name = "Задача 59",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4343),
                            Name = "Задача 60",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4345),
                            Name = "Задача 61",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4347),
                            Name = "Задача 62",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4348),
                            Name = "Задача 63",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4349),
                            Name = "Задача 64",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4351),
                            Name = "Задача 65",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4353),
                            Name = "Задача 66",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4354),
                            Name = "Задача 67",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4356),
                            Name = "Задача 68",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4358),
                            Name = "Задача 69",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4359),
                            Name = "Задача 70",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4361),
                            Name = "Задача 71",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4362),
                            Name = "Задача 72",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4364),
                            Name = "Задача 73",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4365),
                            Name = "Задача 74",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4367),
                            Name = "Задача 75",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4368),
                            Name = "Задача 76",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4370),
                            Name = "Задача 77",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4371),
                            Name = "Задача 78",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4373),
                            Name = "Задача 79",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4374),
                            Name = "Задача 80",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4376),
                            Name = "Задача 81",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4378),
                            Name = "Задача 82",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4379),
                            Name = "Задача 83",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4381),
                            Name = "Задача 84",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4383),
                            Name = "Задача 85",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4385),
                            Name = "Задача 86",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4386),
                            Name = "Задача 87",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4388),
                            Name = "Задача 88",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4389),
                            Name = "Задача 89",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4391),
                            Name = "Задача 90",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4393),
                            Name = "Задача 91",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4394),
                            Name = "Задача 92",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4396),
                            Name = "Задача 93",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4398),
                            Name = "Задача 94",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4400),
                            Name = "Задача 95",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4401),
                            Name = "Задача 96",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4403),
                            Name = "Задача 97",
                            Priority = "Medium"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4405),
                            Name = "Задача 98",
                            Priority = "Low"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4406),
                            Name = "Задача 99",
                            Priority = "High"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 10, 10, 12, 59, 19, 457, DateTimeKind.Utc).AddTicks(4408),
                            Name = "Задача 100",
                            Priority = "High"
                        });
                });

            modelBuilder.Entity("ToDoList.Data.Entities.Note", b =>
                {
                    b.HasOne("ToDoList.Data.Entities.Category", "Category")
                        .WithMany("Notes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ToDoList.Data.Entities.Category", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
